// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4GC0UHKgNJR5nRQtJKeXiqckgY_Rh7k',
    appId: '1:860131151836:web:093e34e51b1f0dadb6c919',
    messagingSenderId: '860131151836',
    projectId: 'online-shop-7b1b3',
    authDomain: 'online-shop-7b1b3.firebaseapp.com',
    storageBucket: 'online-shop-7b1b3.appspot.com',
    measurementId: 'G-H9J1YXYBK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIVxn7E9lRCA7bWad4MQ6S6sM3568_HEQ',
    appId: '1:860131151836:android:aa30f5ff1f11c90db6c919',
    messagingSenderId: '860131151836',
    projectId: 'online-shop-7b1b3',
    storageBucket: 'online-shop-7b1b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ35AC-OES7aHXtcf60Y_ubqm3zDZe2q0',
    appId: '1:860131151836:ios:1d1f3a6ac9594734b6c919',
    messagingSenderId: '860131151836',
    projectId: 'online-shop-7b1b3',
    storageBucket: 'online-shop-7b1b3.appspot.com',
    iosClientId: '860131151836-nlug2sclk2gt85fed6c4n233gnlkdp2b.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.onlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ35AC-OES7aHXtcf60Y_ubqm3zDZe2q0',
    appId: '1:860131151836:ios:8f764c3f96657462b6c919',
    messagingSenderId: '860131151836',
    projectId: 'online-shop-7b1b3',
    storageBucket: 'online-shop-7b1b3.appspot.com',
    iosClientId: '860131151836-p6285i8vejmhsjgev635d71222f9mma5.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.onlineShop.RunnerTests',
  );
}
